### ISSUE TITLE
Initialization of the bias in the last layer of the MLP

### ISSUE THREAD

**Issue by lxxue** [apchenstu/TensoRF#12]
Hi Anpei,

thanks for the awesome work. I want to ask about a small implementation detail:

what is the reason/benefit for initializing the bias to zero here:
https://github.com/apchenstu/TensoRF/blob/3948381077dc68767c2ae27ab6cb7118825efea6/models/tensorBase.py#L72

**Comment by apchenstu** [comment]
Hi, the initialization would not matter a lot, you can also remove it to simplify.

**Comment by lxxue** [comment]
Thanks for the answer!
