### ISSUE TITLE
What is test_dataset.render_path?

### ISSUE THREAD

**Issue by UPstartDeveloper** [apchenstu/TensoRF#21]
Hello, I wanted to ask about a small implementation detail - what is stored in the `test_dataset.render_path` variable? And how is it initialized?

Where this becomes an issue: when I pass `--render_only 1  --render_test 1 --render_path 1` to `train.py` (happy to give the full command if needed), it raises an `AttributeError` on [line 84](https://github.com/apchenstu/TensoRF/blob/ba2c43e73c99cec12be1f4437cbef92ee3f794b9/train.py#L84):
```
c2ws = test_dataset.render_path
```
I think it because `test_dataset.render_path` is `None` for me.

I can at least see that `test_dataset.render_path` is referenced in `train.py` in both the [`reconstruction()`](https://github.com/apchenstu/TensoRF/blob/ba2c43e73c99cec12be1f4437cbef92ee3f794b9/train.py#L294) and [`render_test()`](https://github.com/apchenstu/TensoRF/blob/ba2c43e73c99cec12be1f4437cbef92ee3f794b9/train.py#L84) functions in `train.py`, but I could not locate where exactly it is initialized in any of the `dataLoader` classes. 

Thank you for any insight on this.

**Comment by apchenstu** [comment]
Hi Zain, the "--render_path 1" is for Tank&Template and forward-facing dataset, you just need to pass "--render_test 1" if testing on NeRF or NSVF dataset since their testing path also is a render path

**Comment by UPstartDeveloper** [comment]
Ah ok yhat makes sense why I got the error then, because I was using a Blender dataset.
