### ISSUE TITLE
near_far and bbox for DTU

### ISSUE THREAD

**Issue by basit-7** [apchenstu/TensoRF#33]
Has anyone tested it on DTU? What values should be used for near_far and bbox for DTU? I have tried several values, and got abnormal results everytime.

**Comment by basit-7** [comment]
@apchenstu Hi, I noticed that you've included 'dtu' in dataset_types in opt.py https://github.com/apchenstu/TensoRF/blob/3948381077dc68767c2ae27ab6cb7118825efea6/opt.py#L30

But, there is no datalaoder file for dtu? Could you please share it? It'd help immensely.

**Comment by apchenstu** [comment]
Oh, I didn't test on dtu dataset, I might forget to clean the 'dtu' label since the config is copied from mvsnerf. You can get this file from the mvsnerf repo ( may need some tiny modifications).

**Comment by basit-7** [comment]
Okay thanks!

**Comment by c1enyang** [comment]
@basit-7 Hi, I also got abnormal results on the DTU dataset. Did you succeed at DTU now?

**Comment by basit-7** [comment]
@c1enyang I set near_far to  [2.125, 5] and it worked.
https://github.com/apchenstu/TensoRF/blob/17deeedae5ab4106b30a3295709ec3a8a654c7b1/dataLoader/your_own_data.py#L29

**Comment by ttsesm** [comment]
@basit-7 how do you find what values to use for `near_far` and `scene_bbox`? Or you just play with random values until you get something sufficient?

Thanks.

**Comment by basit-7** [comment]
@ttsesm For a few datasets such as DTU, you can find this information from their documentation or other provided resources. For a custom dataset, you'll have to experiment with values until you get a reasonable result.
