### ISSUE TITLE
Why the occupancy mask is conducted on alpha?

### ISSUE THREAD

**Issue by Trent-tangtao** [apchenstu/TensoRF#44]
Hi, thanks for your great work!
I'm confused why the occupancy mask is conducted on alpha instead of sigma(density)?

**Comment by heyjianjing** [comment]
i think ultimately it is alpha that decides where the ray stops, so it should be a more appropriate choice.

smaller sigma -> smaller alpha, so I guess using sigma should also work in some way. 

but if any transform is needed to make it work, better just use alpha.

**Comment by apchenstu** [comment]
> 
Thanks for the response, yeah that's right!

**Comment by Trent-tangtao** [comment]
Thanks! @heyjianjing @apchenstu
