### ISSUE TITLE
Results with Ignatius not reproducible due to problematic intrinsics file in data

### ISSUE THREAD

**Issue by Shiran-Yuan** [apchenstu/TensoRF#68]
@apchenstu Hi! Thanks for this amazing project. Unfortunately I found that the `intrinsics.txt` file of "Ignatius" in Tanks & Temples seems wrong, as it looks like colmap instead. When I try to replicate results by training TensoRF on Ignatius, it gives the following error:

`ValueError: The number of columns changed from 4 to 3 at row 2.`

Any solutions and fixes? Thanks a bunch in advance.

**Comment by apchenstu** [comment]
https://github.com/sunset1995/DirectVoxGO/issues/4

**Comment by Shiran-Yuan** [comment]
Thank you!
