### ISSUE TITLE
How to build a real-time renderer with TensoRF?

### ISSUE THREAD

**Issue by UPstartDeveloper** [apchenstu/TensoRF#7]
Hello @apchenstu,

I was wondering if it might be possible to render 3D models using TensoRF in real-time? I don't know if this is the direction your team was planning to go in with your paper.  But I am curious if it would be possible to build something similar to what Google built for SNeRG: [website link](https://phog.github.io/snerg/viewer/index.html?dir=https://storage.googleapis.com/snerg/750/lego)

Thanks for sharing this work with the community!

**Comment by apchenstu** [comment]
Hi, thanks for the recommendation, yeah, it is interesting to build a real-time renderer and it's not hard to achieve by combining with a customized CUDA kernel or OpenGL (SNeRG) I think. Unfortunately, the real-time renderer doesn't in our current plan, feel free to design one if you are interested in :)

**Comment by UPstartDeveloper** [comment]
If anyone else finds this problem interesting, I started a [fork](https://github.com/UPstartDeveloper/JAX-TensoRF) of this repo so we can work on it!

The approach I personally think we should take is: 

1. re-implementing all the `torch` modules using `flax`, and 
2. then see if we can drop a trained TensoRF straight into the [`bake.py`](https://github.com/google-research/google-research/blob/master/snerg/bake.py) script that the SNeRG authors first created.

**Comment by cduguet** [comment]
Hi Zain! I find this problem interesting too! Thanks for sharing.

**Comment by UPstartDeveloper** [comment]
Hey team, 

I'm curious if anyone has come across a technique or research paper on 1) reconstructing a 3d mesh from RGB-D scans, 2) in real-time, 3) and for a non-deformable object)?

Reason I ask is because I was able to render the predicted images by TensoRF for a custom dataset I have (here's an example):

![019999_003](https://user-images.githubusercontent.com/35160126/163890671-14ac3f39-b0b8-47c9-a8c9-df8f17961d61.png) 

Since TensoRF visualizes both the RGB values and depth maps, I'm starting to wonder if we could just use these for the reconstruction?

**Comment by UPstartDeveloper** [comment]
^On 2nd thought - I guess using RGB-D would be overthinking the problem?
I know earlier in the issue @apchenstu brought up the following idea:

> Hi, thanks for the recommendation, yeah, it is interesting to build a real-time renderer and it's not hard to achieve by combining with a customized CUDA kernel or OpenGL (SNeRG) I think...

This is probably a dumb question - but could you please elaborate on this? To me what I think it suggests is that we could just pass a trained TensoRF to a custom fragment shader (let's say in OpenGL), and use that to predict the view-dependent colors in real-time?

**Comment by UPstartDeveloper** [comment]
Hi again - just to provide an update on this, I started _another_ new repo called [`tensorfvis`](https://github.com/UPstartDeveloper/tensorfvis) here, where we're building the renderer based on the [`nerfvis`](https://github.com/sxyu/nerfvis) library (which itself is based on the [PlenOctrees](https://alexyu.net/plenoctrees/) paper). I will open up new issues in the future there to continue this discussion.
